"""linear_python — a pragmatic Python client for the Linear GraphQL API."""

from __future__ import annotations

from .client import DEFAULT_ENDPOINT, LinearClient
from .errors import (
    LinearAuthenticationError,
    LinearError,
    LinearGraphQLError,
    LinearNetworkError,
    LinearRateLimitError,
)
from .models.entities import (
    Comment,
    Issue,
    IssueLabel,
    LinearModel,
    PageInfo,
    Project,
    Team,
    User,
    WorkflowState,
)
from .models.requests import (
    CommentCreateRequest,
    CommentRequest,
    CommentsRequest,
    IssueArchiveRequest,
    IssueCreateRequest,
    IssueLabelsRequest,
    IssueRequest,
    IssuesRequest,
    IssueUpdateRequest,
    PaginatedRequest,
    ProjectRequest,
    ProjectsRequest,
    TeamRequest,
    TeamsRequest,
    UserRequest,
    UsersRequest,
    WorkflowStatesRequest,
)
from .models.responses import (
    ArchiveIssueResponse,
    CommentResponse,
    CommentsResponse,
    ConnectionResponse,
    CreateCommentResponse,
    CreateIssueResponse,
    IssueLabelsResponse,
    IssueResponse,
    IssuesResponse,
    ProjectResponse,
    ProjectsResponse,
    TeamResponse,
    TeamsResponse,
    UpdateIssueResponse,
    UserResponse,
    UsersResponse,
    ViewerResponse,
    WorkflowStatesResponse,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_ENDPOINT",
    "LinearClient",
    # errors
    "LinearError",
    "LinearAuthenticationError",
    "LinearRateLimitError",
    "LinearGraphQLError",
    "LinearNetworkError",
    # models
    "LinearModel",
    "Comment",
    "Issue",
    "IssueLabel",
    "PageInfo",
    "Project",
    "Team",
    "User",
    "WorkflowState",
    # requests
    "PaginatedRequest",
    "UserRequest",
    "UsersRequest",
    "TeamRequest",
    "TeamsRequest",
    "IssueRequest",
    "IssuesRequest",
    "IssueCreateRequest",
    "IssueUpdateRequest",
    "IssueArchiveRequest",
    "ProjectRequest",
    "ProjectsRequest",
    "CommentRequest",
    "CommentsRequest",
    "CommentCreateRequest",
    "WorkflowStatesRequest",
    "IssueLabelsRequest",
    # responses
    "ConnectionResponse",
    "ViewerResponse",
    "UserResponse",
    "UsersResponse",
    "TeamResponse",
    "TeamsResponse",
    "IssueResponse",
    "IssuesResponse",
    "CreateIssueResponse",
    "UpdateIssueResponse",
    "ArchiveIssueResponse",
    "ProjectResponse",
    "ProjectsResponse",
    "CommentResponse",
    "CommentsResponse",
    "CreateCommentResponse",
    "WorkflowStatesResponse",
    "IssueLabelsResponse",
    "__version__",
]
