"""Data models: entities, request inputs, and response outputs.

Re-exports everything so you can import from the package directly, e.g.
``from linear_python_client.models import Issue, IssueCreateRequest, IssuesResponse``.
"""

from __future__ import annotations

from .entities import (
    Attachment,
    Comment,
    Cycle,
    Issue,
    IssueDetail,
    IssueLabel,
    IssueRelation,
    LinearModel,
    PageInfo,
    Project,
    Team,
    User,
    WorkflowState,
)
from .requests import (
    CommentCreateRequest,
    CommentRequest,
    CommentsRequest,
    FindWorkflowStateRequest,
    IssueAddLabelRequest,
    IssueArchiveRequest,
    IssueCreateRequest,
    IssueLabelsRequest,
    IssueRemoveLabelRequest,
    IssueRequest,
    IssueSetStateRequest,
    IssuesRequest,
    IssueUpdateRequest,
    PaginatedRequest,
    ProjectRequest,
    ProjectsRequest,
    TeamRequest,
    TeamsRequest,
    UserRequest,
    UsersRequest,
    WorkflowStatesRequest,
)
from .responses import (
    AddLabelResponse,
    ArchiveIssueResponse,
    CommentResponse,
    CommentsResponse,
    ConnectionResponse,
    CreateCommentResponse,
    CreateIssueResponse,
    IssueDetailsResponse,
    IssueLabelsResponse,
    IssueResponse,
    IssuesResponse,
    ProjectResponse,
    ProjectsResponse,
    RemoveLabelResponse,
    TeamResponse,
    TeamsResponse,
    UpdateIssueResponse,
    UserResponse,
    UsersResponse,
    ViewerResponse,
    WorkflowStateResponse,
    WorkflowStatesResponse,
)

__all__ = [
    # entities
    "LinearModel",
    "Attachment",
    "Comment",
    "Cycle",
    "Issue",
    "IssueDetail",
    "IssueLabel",
    "IssueRelation",
    "PageInfo",
    "Project",
    "Team",
    "User",
    "WorkflowState",
    # requests
    "PaginatedRequest",
    "UserRequest",
    "UsersRequest",
    "TeamRequest",
    "TeamsRequest",
    "IssueRequest",
    "IssuesRequest",
    "IssueCreateRequest",
    "IssueUpdateRequest",
    "IssueArchiveRequest",
    "IssueAddLabelRequest",
    "IssueRemoveLabelRequest",
    "IssueSetStateRequest",
    "FindWorkflowStateRequest",
    "ProjectRequest",
    "ProjectsRequest",
    "CommentRequest",
    "CommentsRequest",
    "CommentCreateRequest",
    "WorkflowStatesRequest",
    "IssueLabelsRequest",
    # responses
    "ConnectionResponse",
    "ViewerResponse",
    "UserResponse",
    "UsersResponse",
    "TeamResponse",
    "TeamsResponse",
    "IssueResponse",
    "IssueDetailsResponse",
    "IssuesResponse",
    "CreateIssueResponse",
    "UpdateIssueResponse",
    "ArchiveIssueResponse",
    "AddLabelResponse",
    "RemoveLabelResponse",
    "ProjectResponse",
    "ProjectsResponse",
    "CommentResponse",
    "CommentsResponse",
    "CreateCommentResponse",
    "WorkflowStateResponse",
    "WorkflowStatesResponse",
    "IssueLabelsResponse",
]
