"""linear_python_client — a pragmatic Python client for the Linear GraphQL API."""

from __future__ import annotations

from .client import DEFAULT_ENDPOINT, LinearClient
from .errors import (
    LinearAuthenticationError,
    LinearError,
    LinearGraphQLError,
    LinearNetworkError,
    LinearRateLimitError,
    LinearServerError,
)
from .models.entities import (
    Attachment,
    Comment,
    Cycle,
    Issue,
    IssueDetail,
    IssueLabel,
    IssueRelation,
    IssueSharedAccess,
    LinearModel,
    PageInfo,
    Project,
    Team,
    User,
    WorkflowState,
)
from .models.requests import (
    CommentCreateRequest,
    CommentRequest,
    CommentsRequest,
    FindLabelRequest,
    FindProjectRequest,
    FindTeamRequest,
    FindUserRequest,
    FindWorkflowStateRequest,
    IssueAddLabelRequest,
    IssueArchiveRequest,
    IssueCreateRequest,
    IssueLabelsRequest,
    IssueRemoveLabelRequest,
    IssueRequest,
    IssueSetStateRequest,
    IssueShareRequest,
    IssuesRequest,
    IssueUnshareRequest,
    IssueUpdateRequest,
    PaginatedRequest,
    ProjectRequest,
    ProjectsRequest,
    TeamRequest,
    TeamsRequest,
    UserRequest,
    UsersRequest,
    WorkflowStatesRequest,
)
from .models.responses import (
    AddLabelResponse,
    ArchiveIssueResponse,
    CommentResponse,
    CommentsResponse,
    ConnectionResponse,
    CreateCommentResponse,
    CreateIssueResponse,
    IssueDetailsResponse,
    IssueLabelResponse,
    IssueLabelsResponse,
    IssueResponse,
    IssuesResponse,
    ProjectResponse,
    ProjectsResponse,
    RemoveLabelResponse,
    ShareIssueResponse,
    TeamResponse,
    TeamsResponse,
    UnshareIssueResponse,
    UpdateIssueResponse,
    UserResponse,
    UsersResponse,
    ViewerResponse,
    WorkflowStateResponse,
    WorkflowStatesResponse,
)

__version__ = "0.2.2"

__all__ = [
    "DEFAULT_ENDPOINT",
    "LinearClient",
    # errors
    "LinearError",
    "LinearAuthenticationError",
    "LinearRateLimitError",
    "LinearGraphQLError",
    "LinearNetworkError",
    "LinearServerError",
    # models
    "LinearModel",
    "Attachment",
    "Comment",
    "Cycle",
    "Issue",
    "IssueDetail",
    "IssueLabel",
    "IssueRelation",
    "IssueSharedAccess",
    "PageInfo",
    "Project",
    "Team",
    "User",
    "WorkflowState",
    # requests
    "PaginatedRequest",
    "UserRequest",
    "UsersRequest",
    "TeamRequest",
    "TeamsRequest",
    "IssueRequest",
    "IssuesRequest",
    "IssueCreateRequest",
    "IssueUpdateRequest",
    "IssueArchiveRequest",
    "IssueAddLabelRequest",
    "IssueRemoveLabelRequest",
    "IssueSetStateRequest",
    "IssueShareRequest",
    "IssueUnshareRequest",
    "FindWorkflowStateRequest",
    "FindTeamRequest",
    "FindUserRequest",
    "FindLabelRequest",
    "FindProjectRequest",
    "ProjectRequest",
    "ProjectsRequest",
    "CommentRequest",
    "CommentsRequest",
    "CommentCreateRequest",
    "WorkflowStatesRequest",
    "IssueLabelsRequest",
    # responses
    "ConnectionResponse",
    "ViewerResponse",
    "UserResponse",
    "UsersResponse",
    "TeamResponse",
    "TeamsResponse",
    "IssueResponse",
    "IssueDetailsResponse",
    "IssuesResponse",
    "CreateIssueResponse",
    "UpdateIssueResponse",
    "ArchiveIssueResponse",
    "AddLabelResponse",
    "RemoveLabelResponse",
    "ShareIssueResponse",
    "UnshareIssueResponse",
    "ProjectResponse",
    "ProjectsResponse",
    "CommentResponse",
    "CommentsResponse",
    "CreateCommentResponse",
    "WorkflowStateResponse",
    "WorkflowStatesResponse",
    "IssueLabelResponse",
    "IssueLabelsResponse",
    "__version__",
]
